In [7]:
import duckdb

In [9]:
con = duckdb.connect(database='dados_duckdb.db',read_only=False)

In [10]:
df = con.execute("SELECT * FROM produtos").fetchdf()
df.head()

      ID      Nome Categoria  Fornecedor   Preco
0  10001  PARAFUSO      BT10         100   100.0
1  10002   MARTELO      BT50         100  1500.0
2  10003     PREGO      BT10         100    50.0
3  10004     SERRA      BT50         100   200.0
4  10005   MACHADO      BT50         100   100.0

In [11]:
df2 = df.drop(columns=['Categoria','Fornecedor'])
df2.head(10)

      ID      Nome   Preco
0  10001  PARAFUSO   100.0
1  10002   MARTELO  1500.0
2  10003     PREGO    50.0
3  10004     SERRA   200.0
4  10005   MACHADO   100.0

In [19]:
con.execute("""
     DROP TABLE dim_produtos
""")

In [20]:
con.execute("""
    CREATE TABLE IF NOT EXISTS dim_produtos(
    id_produto BIGINT,
    Nome_produto TEXT,
    Preco_produto FLOAT
    )
""")

In [24]:
con.execute("INSERt INTO dim_produtos SELECT * FROM df2")

In [25]:
df_Dim = con.execute("SELECT * FROM dim_produtos").fetchdf()
df_Dim.head()

   id_produto Nome_produto  Preco_produto
0       10001     PARAFUSO          100.0
1       10002      MARTELO         1500.0
2       10003        PREGO           50.0
3       10004        SERRA          200.0
4       10005      MACHADO          100.0

In [26]:
con.close()